### ISSUE TITLE
Bulk Upload: Mekelle

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#114]
Mekelle data and metadata are ready for upload. They can be found here:

https://drive.google.com/open?id=0B2Oc3HZSI7QFdlE3Z1k4SzhaSFk

**Comment by kalxas** [comment]
Bulk Upload result:
```
Found 12 potential layers.
[created] Layer for '/home/ubuntu/Mekelle_Data/Fuel_Station.shp' (1/12)
[failed] Layer for '/home/ubuntu/Mekelle_Data/Market_Place.shp' (2/12)
[created] Layer for '/home/ubuntu/Mekelle_Data/College_and_University.shp' (3/12)
[created] Layer for '/home/ubuntu/Mekelle_Data/Govt_NGO_Offices.shp' (4/12)
[created] Layer for '/home/ubuntu/Mekelle_Data/Sport_Area.shp' (5/12)
[created] Layer for '/home/ubuntu/Mekelle_Data/Hotel.shp' (6/12)
[created] Layer for '/home/ubuntu/Mekelle_Data/Police_Station.shp' (7/12)
[created] Layer for '/home/ubuntu/Mekelle_Data/School.shp' (8/12)
[created] Layer for '/home/ubuntu/Mekelle_Data/Bank_and_finance.shp' (9/12)
[created] Layer for '/home/ubuntu/Mekelle_Data/Religious.shp' (10/12)
[created] Layer for '/home/ubuntu/Mekelle_Data/Museums_and_Memorials.shp' (11/12)
[created] Layer for '/home/ubuntu/Mekelle_Data/Hospital.shp' (12/12)
Detailed report of failures:


/home/ubuntu/Mekelle_Data/Market_Place.shp
================
Traceback (most recent call last):
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/geonode/layers/utils.py", line 625, in upload
    metadata_uploaded_preserve=metadata_uploaded_preserve
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/geonode/layers/utils.py", line 499, in file_upload
    defaults=defaults
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 389, in get_or_create
    return super(MultilingualQuerySet, self).get_or_create(**kwargs)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/query.py", line 407, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/query.py", line 439, in _create_object_from_params
    obj = self.create(**params)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 381, in create
    return super(MultilingualQuerySet, self).create(**kwargs)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/polymorphic/models.py", line 74, in save
    return super(PolymorphicModel, self).save(*args, **kwargs) 
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 758, in save_base
    update_fields=update_fields)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)   
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/geonode/geoserver/signals.py", line 93, in geoserver_pre_save
    charset=instance.charset)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/geonode/geoserver/helpers.py", line 1128, in geoserver_upload
    workspace=workspace)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/geonode/geoserver/helpers.py", line 1005, in _create_db_featurestore
    raise GeoNodeException(msg)
GeoNodeException: An exception occurred loading data to PostGIS- java.io.IOException: transform error


Finished processing 12 layers in 82.0 seconds.

11 Created layers
0 Updated layers
0 Skipped layers
1 Failed layers
6.833333 seconds per layer
```

**Comment by kalxas** [comment]
Metadata update result:
```
Mekelle: Banking and Finance : Metadata updated!
Mekelle: Colleges and Universities : Metadata updated!
Mekelle: Fuel Stations : Metadata updated!
Mekelle: Government and Non-Government Offices : Metadata updated!
Mekelle: Hospital : Metadata updated!
Mekelle: Hotel and Services : Metadata updated!
mekelle: market places : Failed to update
Exception: Layer matching query does not exist.
Mekelle: Museums and Memorials : Metadata updated!
Mekelle: Police Station : Metadata updated!
Mekelle: Churches and Religious Sites : Metadata updated!
Mekelle: Schools and Educational Institutes : Metadata updated!
Mekelle: Sport Center : Metadata updated!
```

**Comment by kalxas** [comment]
Data uploaded to http://2c.terranodo.io

**Comment by kalxas** [comment]
Data uploaded to http://secondarycities.geonode.state.gov/
