### ISSUE TITLE
Bulk Upload: Denpasar ALL Partner Provided

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#135]
Denpasar data layers are ready to be uploaded. The data and metadata spreadsheet can be found here: 
https://drive.google.com/drive/folders/0B2Oc3HZSI7QFYlFZX2VOUzRzeEU?usp=sharing

**Comment by d3netxer** [comment]
The Waste_Bank.shp failed to be uploaded, error message:

/home/ubuntu/Denpasar_ALL_Partner_Provided/Waste_Bank.shp
================
Traceback (most recent call last):
  File "/home/ubuntu/venvs/state_2c_geonode/src/geonode/geonode/layers/utils.py", line 625, in upload
    metadata_uploaded_preserve=metadata_uploaded_preserve
  File "/home/ubuntu/venvs/state_2c_geonode/src/geonode/geonode/layers/utils.py", line 499, in file_upload
    defaults=defaults
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 389, in get_or_create
    return super(MultilingualQuerySet, self).get_or_create(**kwargs)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/query.py", line 407, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/query.py", line 439, in _create_object_from_params
    obj = self.create(**params)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 381, in create
    return super(MultilingualQuerySet, self).create(**kwargs)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/polymorphic/models.py", line 72, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 761, in save_base
    self._save_parents(cls, using, update_fields)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 786, in _save_parents
    self._save_table(cls=parent, using=using, update_fields=update_fields)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 973, in execute_sql
    for sql, params in self.as_sql():
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 931, in as_sql
    for obj in self.query.objs
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1627, in get_db_prep_save
    self.max_digits, self.decimal_places)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/backends/base/operations.py", line 477, in value_to_db_decimal
    return utils.format_number(value, max_digits, decimal_places)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 200, in format_number
    value = value.quantize(decimal.Decimal(".1") ** decimal_places, context=context)
  File "/usr/lib/python2.7/decimal.py", line 2442, in quantize
    'quantize with one INF')
  File "/usr/lib/python2.7/decimal.py", line 3873, in _raise_error
    raise error(explanation)
InvalidOperation: quantize with one INF

**Comment by kalxas** [comment]
same error as in #137

**Comment by kalxas** [comment]
When a layer starts with a number in the filename, GeoNode adds an underscore in the layer name.

**Comment by kalxas** [comment]
Metadata update (2nd try)
```
Denpasar:  Three Villages Boundary and Waste Collectors : Metadata updated!
Denpasar:  Three Villages Boundary and Waste Customers : Metadata updated!
Denpasar:  Three Villages Boundary and Waste Drivers : Metadata updated!
Denpasar:  Three Villages Boundary and Villages Officer : Metadata updated!
Denpasar: Waste Management and Villages  : Metadata updated!
Denpasar: Armroll Facilities : Metadata updated!
Denpasar: Big Waste Haulers : Metadata updated!
Denpasar: City Boundary and Village Limits : Metadata updated!
Denpasar: Illegal Dumping Area : Metadata updated!
Denpasar: Integrated Waste Facilities : Metadata updated!
Kesiman Kertalangu: Village Boundary : Metadata updated!
Denpasar: Temporary Waste Tipping Area : Metadata updated!
Pemecutan Kaja: Village Boundary : Metadata updated!
Denpasar: Public waste depot : Metadata updated!
Denpasar: Recycling Factory : Metadata updated!
Sanur kaja: Village Boundary : Metadata updated!
Sanur Kaja: Customers Waste : Metadata updated!
tegal kertha: village boundary : Failed to update
Exception: Layer matching query does not exist.
denpasar: waste bank : Failed to update
Exception: Layer matching query does not exist.
Denpasar: Waste Collectors : Metadata updated!
Denpasar: Waste Recycler : Metadata updated!
```

**Comment by kalxas** [comment]
new upload:
```
Verifying that GeoNode is running ...

Found 20 potential layers.

[failed] Layer for '/home/ubuntu/Denpasar_Data/Waste_Bank.shp' (1/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/Denpasar_city.shp' (2/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/Recycling_factory.shp' (3/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/Pemecutan_Kaja.shp' (4/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/Sanur_kaja_Village.shp' (5/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/Integrated_waste_facility.shp' (6/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/Armroll.shp' (7/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/Waste_Collector.shp' (8/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/Sanur_kaja_customer.shp' (9/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/Waste_Recycler.shp' (10/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/Kesiman_Kertalangu.shp' (11/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/Big_Waste_Haulers.shp' (12/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/3_Villages_Officer.shp' (13/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/All_denpasar_villages.shp' (14/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/Public_waste_depot.shp' (15/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/Legal_dump_site.shp' (16/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/3_Villages_Customers.shp' (17/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/3_Villages_Drivers.shp' (18/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/Illegal_dumping.shp' (19/20)

[created] Layer for '/home/ubuntu/Denpasar_Data/3_Villages_Collectors.shp' (20/20)
```

**Comment by kalxas** [comment]
@sophialinn I can see that the Denpasar: prefix is not used on all layers here. Is that ok?

**Comment by sophialinn** [comment]
Not OK. We should add "Denpasar:" then the village name, so for example:  "Denpasar: Kesiman Kertalangu Village Boundary."  I have made changes to the spreadsheet BUT for some reason I am not able to see all rows in the spreadsheet--it's as if some are hidden or locked. Do you see that?

**Comment by sophialinn** [comment]
"Waste_Bank" data set had many empty features. I deleted them and re-uploaded the data (shapefile) to the Google Drive. The metadata sheet should be good to go too.

**Comment by d3netxer** [comment]
@sophialinn I figured out that column J was being filtered so some of the rows were not displaying. I changed the filter to select all of the values so you can see all of the rows now. You just have row 18 left to update (Sanur Kaja: Customers Waste)!

**Comment by sophialinn** [comment]
Thanks, Tom. I've made that update so the whole spreadsheet *should* be ready to go. (And see if "Waste_Bank" works now too.)

**Comment by d3netxer** [comment]
Thanks Sophia!

**Comment by d3netxer** [comment]
Waste_Bank.shp failed to import again, same error as before.

**Comment by d3netxer** [comment]
ok I just ran the metadata script again now to update the layer names with the new titles

**Comment by sophialinn** [comment]
There's a new metadata spreadsheet and data folder exclusively for the "Denpasar Water Bank" dataset. See if you can get this to upload.
 https://drive.google.com/drive/folders/0B2Oc3HZSI7QFYlFZX2VOUzRzeEU?usp=sharing

**Comment by d3netxer** [comment]
I tried uploading the new Waste Bank shapefile today and it failed. Then I downloaded the file locally and tried saving new versions in QGIS and re-uploading the file to the server and trying again the import, but it kept on failing. I saved the points to CSV, then imported the CSV back into QGIS and then saved as a shapefile. This failed as well. I then started deleting some of the columns, this failed as well. With the most recent file, I made the X and Y coordinates only display 4 decimal points and this time the import worked finally.

I think I will delete the file now, and try again going up to 5 decimal points and with all the fields

**Comment by d3netxer** [comment]
tom [3:52 PM] 
something else seems is at play that is making debugging harder. For @kalxas : I have two shapefiles that are the same in the home directory in separate folders. The shapefile in the waste_bank12 folder is named Waste_Bank. The shapefile in the waste_bank13 folder is called Waste_Bank13. However Waste_Bank13 uploads, but Waste_Bank from the waste_bank12 folder fails with the same "quantize with on ING" error. This happens even if the Waste_Bank file is deleted from the 2C GeoNode admin. 

I don't know what is going on. This is the command I am using:
```
(state_2c_geonode) ubuntu@ip-172-31-5-84:~/state_2c_geonode$ python manage.py importlayers --verbosity=2 --overwrite --user=2C_Denpasar /home/ubuntu/waste_bank12/
```
the Waste_Bank files was deleted from the GeoNode admin, so I don't know why it is giving an error, while the same file successfully uploads if the name changes. The --overwrite flag is used anyways so even if Waste_Bank already existed it should be overwritten. Maybe something else is being retained somewhere so that the error is being returned even if the file should work?
