### ISSUE TITLE
Bulk Upload: Port Harcourt Partner Provided

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#137]
Data and metadata are ready for upload and can be found here:
https://drive.google.com/drive/folders/0B2Oc3HZSI7QFc3ktMXJPajd1X0E?usp=sharing

**Comment by d3netxer** [comment]
1) There are some failures after running the reproject_vectors.shp
```ubuntu@ip-172-31-5-84:~$ ./reproject_vectors.sh /home/ubuntu/Port_Harcourt_Partner_Provided_Data/
Reprojecting 2CPH_ACADEMIC_INSTITUTIONS_2007.shp
Can't transform coordinates, source layer has no
coordinate system. Use -s_srs to set one.
ERROR 1: Terminating translation prematurely after failed
translation of layer 2CPH_ACADEMIC_INSTITUTIONS_2007 (use -skipfailures to skip errors)

Reprojecting 2CPH_ACADEMIC_INSTITUTIONS_2017.shp
Warning 1: One or several characters couldn't be converted correctly from UTF-8 to ISO-8859-1.
This warning will not be emitted anymore.
Reprojecting 2CPH_FINANCIAL_2007.shp
Reprojecting 2CPH_FINANCIAL_2017.shp
Warning 1: One or several characters couldn't be converted correctly from UTF-8 to ISO-8859-1.
This warning will not be emitted anymore.
Reprojecting 2CPH_FLOODING_HOTSPOTS_ZONE_2017.shp
Reprojecting 2CPH_GOVERNMENT_AGENCY_2017.shp
Reprojecting 2CPH_HEALTH_FACILITIES_2017.shp
Reprojecting 2CPH_LOCALGOVERNMENTAREA_2017.shp
Reprojecting 2CPH_PORTHARCOURT_INITIAL_EXTENT.shp
Reprojecting 2CPH_PUBLIC_SAFETY_2017.shp
Warning 1: One or several characters couldn't be converted correctly from UTF-8 to ISO-8859-1.
This warning will not be emitted anymore.
Reprojecting 2CPH_RELIGIOUS_ESTABLISHMENTS_2007.shp
Can't transform coordinates, source layer has no
coordinate system. Use -s_srs to set one.
ERROR 1: Terminating translation prematurely after failed
translation of layer 2CPH_RELIGIOUS_ESTABLISHMENTS_2007 (use -skipfailures to skip errors)```

**Comment by d3netxer** [comment]
2) During the import, 2 layers failed
```
(state_2c_geonode) ubuntu@ip-172-31-5-84:~/state_2c_geonode$ python manage.py importlayers --verbosity=2 --user=2C_Port_Harcourt /home/u                                                     buntu/Port_Harcourt_Partner_Provided_Data/
System check identified some issues:
WARNINGS:
base.ResourceBase.tkeywords: (fields.W340) null has no effect on ManyToManyField.
Verifying that GeoNode is running ...
Found 13 potential layers.
[created] Layer for '/home/ubuntu/Port_Harcourt_Partner_Provided_Data/2CPH_PORTHARCOURT_INITIAL_EXTENT.shp' (1/13)
[failed] Layer for '/home/ubuntu/Port_Harcourt_Partner_Provided_Data/2CPH_ACADEMIC_INSTITUTIONS_2017.shp' (2/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Partner_Provided_Data/2CPH_HEALTH_FACILITIES_2017.shp' (3/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Partner_Provided_Data/2CPH_GOVERNMENT_AGENCY_2017.shp' (4/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Partner_Provided_Data/2CPH_FLOODING_HOTSPOTS_ZONE_2017.shp' (5/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Partner_Provided_Data/2CPH_FINANCIAL_2017.shp' (6/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Partner_Provided_Data/2CPH_FINANCIAL_2007.shp' (7/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Partner_Provided_Data/2CPH_ACADEMIC_INSTITUTIONS_2007.shp' (8/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Partner_Provided_Data/2CPH_RELIGIOUS_ESTABLISHMENTS_2007.shp' (9/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Partner_Provided_Data/2C_RECREATIONAL_2017.shp' (10/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Partner_Provided_Data/2CPH_LOCALGOVERNMENTAREA_2017.shp' (11/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Partner_Provided_Data/2CPH_PUBLIC_SAFETY_2017.shp' (12/13)
[failed] Layer for '/home/ubuntu/Port_Harcourt_Partner_Provided_Data/2CPH_RELIGIOUS_ESTABLISHMENTS_2017.shp' (13/13)
Detailed report of failures:
/home/ubuntu/Port_Harcourt_Partner_Provided_Data/2CPH_ACADEMIC_INSTITUTIONS_2017.shp
================
Traceback (most recent call last):
  File "/home/ubuntu/venvs/state_2c_geonode/src/geonode/geonode/layers/utils.py", line 625, in upload
    metadata_uploaded_preserve=metadata_uploaded_preserve
  File "/home/ubuntu/venvs/state_2c_geonode/src/geonode/geonode/layers/utils.py", line 499, in file_upload
    defaults=defaults
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 389, in get_or_create
    return super(MultilingualQuerySet, self).get_or_create(**kwargs)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/query.py", line 407, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/query.py", line 439, in _create_object_fr                                                     om_params
    obj = self.create(**params)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 381, in create
    return super(MultilingualQuerySet, self).create(**kwargs)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/polymorphic/models.py", line 72, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 761, in save_base
    self._save_parents(cls, using, update_fields)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 786, in _save_parents
    self._save_table(cls=parent, using=using, update_fields=update_fields)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 973, in execute_sq                                                     l
    for sql, params in self.as_sql():
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 931, in as_sql
    for obj in self.query.objs
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1627, in get_db                                                     _prep_save
    self.max_digits, self.decimal_places)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/backends/base/operations.py", line 477, in value                                                     _to_db_decimal
    return utils.format_number(value, max_digits, decimal_places)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 200, in format_number
    value = value.quantize(decimal.Decimal(".1") ** decimal_places, context=context)
  File "/usr/lib/python2.7/decimal.py", line 2442, in quantize
    'quantize with one INF')
  File "/usr/lib/python2.7/decimal.py", line 3873, in _raise_error
    raise error(explanation)
InvalidOperation: quantize with one INF
/home/ubuntu/Port_Harcourt_Partner_Provided_Data/2CPH_RELIGIOUS_ESTABLISHMENTS_2017.shp
================
Traceback (most recent call last):
  File "/home/ubuntu/venvs/state_2c_geonode/src/geonode/geonode/layers/utils.py", line 625, in upload
    metadata_uploaded_preserve=metadata_uploaded_preserve
  File "/home/ubuntu/venvs/state_2c_geonode/src/geonode/geonode/layers/utils.py", line 499, in file_upload
    defaults=defaults
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 389, in get_or_create
    return super(MultilingualQuerySet, self).get_or_create(**kwargs)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/query.py", line 407, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/query.py", line 439, in _create_object_fr                                                     om_params
    obj = self.create(**params)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 381, in create
    return super(MultilingualQuerySet, self).create(**kwargs)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/polymorphic/models.py", line 72, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 761, in save_base
    self._save_parents(cls, using, update_fields)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 786, in _save_parents
    self._save_table(cls=parent, using=using, update_fields=update_fields)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 973, in execute_sq                                                     l
    for sql, params in self.as_sql():
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 931, in as_sql
    for obj in self.query.objs
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1627, in get_db                                                     _prep_save
    self.max_digits, self.decimal_places)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/backends/base/operations.py", line 477, in value                                                     _to_db_decimal
    return utils.format_number(value, max_digits, decimal_places)
  File "/home/ubuntu/venvs/state_2c_geonode/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 200, in format_number
    value = value.quantize(decimal.Decimal(".1") ** decimal_places, context=context)
  File "/usr/lib/python2.7/decimal.py", line 2442, in quantize
    'quantize with one INF')
  File "/usr/lib/python2.7/decimal.py", line 3873, in _raise_error
    raise error(explanation)
InvalidOperation: quantize with one INF
Finished processing 13 layers in 73.0 seconds.
11 Created layers
0 Updated layers
0 Skipped layers
2 Failed layers
5.615385 seconds per layer
```

**Comment by d3netxer** [comment]
3) I tried running the update_metadata.py script, and it wasn't able to work on any of the uploaded layers

**Comment by sophialinn** [comment]
This looks like it might be a coordinate system error from the original data from Port Harcourt. I'll look into it.

**Comment by kalxas** [comment]
Some comments about the above errors:
1. Looks like some files do not have a projection defined.
2. The 2 layers not uploading seem to have an issue with infinity values, we need to investigate.
3. Metadata upload should of work, I can review the spreadsheet for errors.

**Comment by kalxas** [comment]
About metadata update: it seems that all data uploaded had a leading space in their name, so GeoNode added an underscore in front of the layer name:
http://secondarycities.geonode.state.gov/layers/geonode:_2cph_portharcourt_initial_extent#map=18.375766550182792/783071.45/530825.61/0

_2cph_portharcourt_initial_extent
So this has to be fixed either on the filenames (and re-upload) or in the spreadsheet...

**Comment by sophialinn** [comment]
Ah! OK. I'll do that.

**Comment by kalxas** [comment]
actually I cannot find the leading space in the filenames, so perhaps this was done because of multiple upload trials?

**Comment by kalxas** [comment]
Metadata issue fixed:
```
$ python update_metadata.py Port\ Harcourt\ Metadata\ Spreadsheet.csv 
Port Harcourt: Recreational Spots : Metadata updated!
Port Harcourt: Academic Institutions (2007) : Metadata updated!
port harcourt: academic institutions (2017) : Failed to update
Exception: Layer matching query does not exist.
Port Harcourt: Financial Establishments (2007) : Metadata updated!
Port Harcourt: Financial Establishments (2017) : Metadata updated!
Port Harcourt: Flooding Hotspots : Metadata updated!
Port Harcourt: Government Agencies : Metadata updated!
Port Harcourt: Public Health Facilities : Metadata updated!
Port Harcourt: Local Government Area : Metadata updated!
Port Harcourt: Initial Boundary of the City Limit : Metadata updated!
Port Harcourt: Public Safety Establishments : Metadata updated!
Port Harcourt: Religious Establishments (2007) : Metadata updated!
port harcourt: religious establishments (2017) : Failed to update
Exception: Layer matching query does not exist.
```

**Comment by sophialinn** [comment]
Observations: The two layers above that "Failed to Update" have different capitalization properties than all of the others. Could that be the problem?

**Comment by kalxas** [comment]
This is because the upload script and geonode convert all layer names to lower case.
Not an issue here.

**Comment by kalxas** [comment]
Same import error on beta site:
```
Found 13 potential layers.

[created] Layer for '/home/ubuntu/Port_Harcourt_Data/2C_RECREATIONAL_2017.shp' (1/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Data/2CPH_LOCALGOVERNMENTAREA_2017.shp' (2/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Data/2CPH_FINANCIAL_2017.shp' (3/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Data/2CPH_ACADEMIC_INSTITUTIONS_2007.shp' (4/13)
[failed] Layer for '/home/ubuntu/Port_Harcourt_Data/2CPH_RELIGIOUS_ESTABLISHMENTS_2017.shp' (5/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Data/2CPH_PORTHARCOURT_INITIAL_EXTENT.shp' (6/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Data/2CPH_PUBLIC_SAFETY_2017.shp' (7/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Data/2CPH_RELIGIOUS_ESTABLISHMENTS_2007.shp' (8/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Data/2CPH_GOVERNMENT_AGENCY_2017.shp' (9/13)
[failed] Layer for '/home/ubuntu/Port_Harcourt_Data/2CPH_ACADEMIC_INSTITUTIONS_2017.shp' (10/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Data/2CPH_FLOODING_HOTSPOTS_ZONE_2017.shp' (11/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Data/2CPH_HEALTH_FACILITIES_2017.shp' (12/13)
[created] Layer for '/home/ubuntu/Port_Harcourt_Data/2CPH_FINANCIAL_2007.shp' (13/13)
```

**Comment by kalxas** [comment]
Metadata update on beta:
```
Port Harcourt: Recreational Spots : Metadata updated!
Port Harcourt: Academic Institutions (2007) : Metadata updated!
port harcourt: academic institutions (2017) : Failed to update
Exception: Layer matching query does not exist.
Port Harcourt: Financial Establishments (2007) : Metadata updated!
Port Harcourt: Financial Establishments (2017) : Metadata updated!
Port Harcourt: Flooding Hotspots : Metadata updated!
Port Harcourt: Government Agencies : Metadata updated!
Port Harcourt: Public Health Facilities : Metadata updated!
Port Harcourt: Local Government Area : Metadata updated!
Port Harcourt: Initial Boundary of the City Limit : Metadata updated!
Port Harcourt: Public Safety Establishments : Metadata updated!
Port Harcourt: Religious Establishments (2007) : Metadata updated!
port harcourt: religious establishments (2017) : Failed to update
Exception: Layer matching query does not exist.
```

**Comment by kalxas** [comment]
On the beta site, I did not need to add underscore before the name in spreadsheet.

**Comment by sophialinn** [comment]
port harcourt: academic institutions (2017) : Failed to update
     Exception: Layer matching query does not exist.
port harcourt: religious establishments (2017) : Failed to update
     Exception: Layer matching query does not exist.

I can't see on my end where the disconnect may be. The filenames appear to be identical between the metadata sheet and the files themselves.

**Comment by kalxas** [comment]
Those layers failed to be uploaded, so they do not exist in the layers list.

**Comment by kalxas** [comment]
I just re-uploaded, no leading underscore issue.
Those 2 layers still fail to upload with the same error

**Comment by sophialinn** [comment]
Emails sent to local partner in Port Harcourt (Daniel Obriango) on Dec. 3 and Dec. 19 to request these two datasets be resent. No response received yet.

**Comment by arshores** [comment]
Just checked and this layer seems to be functioning so I am going to close this issue.
