### ISSUE TITLE
BULK UPLOAD: Pemba Bounding Box Metadata

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#197]
This is a SINGLE metadata update to use as a test. It should replace the existing metadata for the Pemba Bounding Box. NOTE: This is a test to see if we can/should ever update metadata without uploading its data at the same time. In a case like this, it *might* be easier to use the UI to correct metadata problems (Edit Metadata). Again, just testing.

[https://drive.google.com/open?id=1avmyeJ0f1HwW_0LQJKSZXP563opZPtHyOJPW0w_HRGc](url)

**Comment by kalxas** [comment]
```
root@f54586599755:/usr/src/sc/scripts# python update_metadata.py /data/Pemba_BB_metad[38/119]
.csv                                                                                         
Exception while publishing message: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geonode/messaging/producer.py", line 71, in s$
nc_if_local_memory                               
    worker.run(timeout=broker_socket_timeout)                                                
  File "/usr/local/lib/python2.7/site-packages/kombu/mixins.py", line 170, in run
    for _ in self.consume(limit=None, **kwargs):
  File "/usr/local/lib/python2.7/site-packages/kombu/mixins.py", line 192, in consume        
    conn.drain_events(timeout=safety_interval)
  File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 315, in drain_even$
s                                                                                            
    return self.transport.drain_events(self.connection, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 963, in
 drain_events
    get(self._deliver, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/kombu/utils/scheduling.py", line 56, in get
    return self.fun(resource, callback, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 1001, i
n _drain_channel
    return channel.drain_events(callback=callback, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 745, in
 drain_events
    return self._poll(self.cycle, callback, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 402, in
 _poll
   return cycle.get(callback)                                                       [12/119]
  File "/usr/local/lib/python2.7/site-packages/kombu/utils/scheduling.py", line 56, in get
    return self.fun(resource, callback, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 406, in
 _get_and_deliver
    callback(message, queue)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 983, in
 _deliver
    callback(message)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 633, in
 _callback
    return callback(message)
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 624, in _receive_cal
lback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 590, in receive
    [callback(body, message) for callback in callbacks]
  File "/usr/local/lib/python2.7/site-packages/geonode/messaging/consumer.py", line 104, in o
n_geoserver_messages
    geoserver_post_save_local(layer)
  File "/usr/local/lib/python2.7/site-packages/geonode/decorators.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geonode/geoserver/signals.py", line 148, in ge
oserver_post_save_local
    workspace=instance.workspace)
  File "/usr/local/lib/python2.7/site-packages/geoserver/catalog.py", line 932, in get_resour
ce
    resources = self.get_resources(names=name, stores=[store], workspaces=[workspace])
  File "/usr/local/lib/python2.7/site-packages/geoserver/catalog.py", line 910, in get_resour
ces
    resources.extend(s.get_resources())
AttributeError: 'NoneType' object has no attribute 'get_resources'

pemba: bounding box : Failed to update
Exception: 'NoneType' object has no attribute 'get_resources'
```

**Comment by kalxas** [comment]
This error is thrown on ```layer.save()```
