### ISSUE TITLE
User interface won't allow for uploads

### ISSUE THREAD

**Issue by arshores** [state-hiu/2C-GeoNode#198]
Today Tom and I tried using the UI to upload shapefiles one at a time and it isn't functioning. Received a message saying unexpected error.

**Comment by ingenieroariel** [comment]
Checking now, got the following in the logs after updating urls to the new one:

```
geoserver4sc     | 
django4sc        | Unexpected error in upload step
django4sc        | Traceback (most recent call last):
django4sc        |   File "/usr/local/lib/python2.7/site-packages/geonode/upload/views.py", line 650, in view
django4sc        |     resp = _steps[step](req, upload_session)
django4sc        |   File "/usr/local/lib/python2.7/site-packages/geonode/upload/views.py", line 425, in check_step_view
django4sc        |     return next_step_response(request, upload_session)
django4sc        |   File "/usr/local/lib/python2.7/site-packages/geonode/upload/utils.py", line 382, in next_step_response
django4sc        |     return run_response(req, upload_session)
django4sc        |   File "/usr/local/lib/python2.7/site-packages/geonode/upload/utils.py", line 619, in run_response
django4sc        |     run_import(upload_session)
django4sc        |   File "/usr/local/lib/python2.7/site-packages/geonode/upload/utils.py", line 591, in run_import
django4sc        |     task.set_target(target.name, target.workspace.name)
django4sc        |   File "/usr/local/lib/python2.7/site-packages/gsimporter/api.py", line 294, in set_target
django4sc        |     self.target.change_datastore(store_name, workspace)
django4sc        |   File "/usr/local/lib/python2.7/site-packages/gsimporter/api.py", line 220, in change_datastore
django4sc        |     self._client().put_json(self._url(None), json.dumps(target_rep))
django4sc        |   File "/usr/local/lib/python2.7/site-packages/gsimporter/client.py", line 157, in put_json
django4sc        |     "Content-type" : "application/json"
django4sc        |   File "/usr/local/lib/python2.7/site-packages/gsimporter/client.py", line 177, in _request
django4sc        |     resp = self.http.request(method, url, body=data, headers=headers, preload_content=False)
django4sc        |   File "/usr/local/lib/python2.7/site-packages/urllib3/request.py", line 72, in request
django4sc        |     **urlopen_kw)
django4sc        |   File "/usr/local/lib/python2.7/site-packages/urllib3/request.py", line 150, in request_encode_body
django4sc        |     return self.urlopen(method, url, **extra_kw)
django4sc        |   File "/usr/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 324, in urlopen
django4sc        |     response = conn.urlopen(method, u.request_uri, **kw)
django4sc        |   File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
django4sc        |     **response_kw)
django4sc        |   File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
django4sc        |     **response_kw)
django4sc        |   File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
django4sc        |     **response_kw)
django4sc        |   File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
django4sc        |     _stacktrace=sys.exc_info()[2])
django4sc        |   File "/usr/local/lib/python2.7/site-packages/urllib3/util/retry.py", line 399, in increment
django4sc        |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
nginx4sc         | 200.116.231.18 - - [22/Aug/2019:18:15:35 +0000] "GET /upload/check?id=21&force_ajax=true HTTP/2.0" 400 301 "https://secondarycities.geonode.state.gov/layers/upload" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
django4sc        | MaxRetryError: HTTPSConnectionPool(host=u'geoserver', port=8080): Max retries exceeded with url: /geoserver/rest/imports/21/tasks/0/target (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')],)",),))
django4sc        | [pid: 123|app: 0|req: 21/50] 200.116.231.18 () {46 vars in 884 bytes} [Thu Aug 22 18:15:34 2019] GET /upload/check?id=21&force_ajax=true => generated 301 bytes in 312 msecs (HTTP/2.0 400) 8 headers in 306 bytes (1 switches on core 1)
nginx4sc         | 46.229.168.138 - - [22/Aug/2019:18:15:49 +0000] "GET /layers/geonode:pok_elevation_30m_srtmdist2streams HTTP/1.1" 301 175 "-" "Mozilla/5.0 (compatible; SemrushBot/6~bl; +http://www.semrush.com/bot.html)"
db4sc            | 2019-08-22 18:15:51.232 UTC [130] ERROR:  relation "geonode_themes_geonodethemecustomization" does not exist at character 7266
```

**Comment by ingenieroariel** [comment]
This is the issue:

```
django4sc        | url: https://geoserver:8080/geoserver/rest/imports/24/tasks/0/target
```

Geoserver is trying to be accessed on https because the original request comes through that. It should use http since it is internal.

**Comment by ingenieroariel** [comment]
This has been fixed.

![image](https://user-images.githubusercontent.com/54999/63543161-c1d59400-c4e7-11e9-8bb4-b6b9fa9a4507.png)

**Comment by kalxas** [comment]
Thanks @ingenieroariel

**Comment by arshores** [comment]
Do I have login privileges yet? I can check this out and close the ticket once I do.

**Comment by kalxas** [comment]
I have opened #204 to remember...

**Comment by kalxas** [comment]
I think this one is fixed now, right?

**Comment by kalxas** [comment]
I have tested this on the development server and worked for me.
